name: GIOSKETCH
favicon: null
layout_spectrum: 0.97909
typography_spectrum: 0.08165779337286949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a8e4'
    - '#000000'
    - '#f7f04d'
    - '#f22434'
    - '#2d5122'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
