name: GIOSKETCH
favicon: null
layout_spectrum: 0.97909
typography_spectrum: 0.08165779337286949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68318a'
    - '#ffffff'
    - '#bababa'
    - '#000000'
    - '#d54231'
  brandStrength: 0.1875
  lightness: 0.27430800162255764
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
