name: GIOSKETCH
favicon: null
layout_spectrum: 0.21005059871822596
typography_spectrum: 0.08165779337286949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.04500785144045949
  lightness: 0.27430800162255764
  saturation: 0.42894017579965293
  rhythmicContrast: 0.0938059720210731
purpose: []
